In [1]:
import numpy as np
import pandas as pd
from nltk.classify import NaiveBayesClassifier
from nltk.corpus import subjectivity
from nltk.sentiment import SentimentAnalyzer
from nltk.sentiment.util import *

/home/batman/anaconda3/lib/python3.6/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "

In [2]:
# Reading the saved data pickle file
df_stocks = pd.read_pickle('Data/Pickled ten year filtered data (Articles + DJIA).pkl')

In [3]:
df_stocks.articles[2]

". Google Answer to Filling Jobs Is an Algorithm. Germany: Daimler in Deal Over Suit. Israeli Admits Big Errors in Lebanon War, but Won’t Resign. Global Rally on First Day of Trading in New Year. As Costs of Wildfires Grow, So Does a Question: Who Should Pay?. Protecting Internet Democracy. Same-Sex Marriage Setback in Massachusetts. Ford Will Quit Minivan Market. California: 10 Arrested in War Protest. China and Taiwan Exchange Traditional Barbs. Euro-Wary Slovenians Already Miss Their Tolar. Copters Drop Food for People and Cattle Trapped by Snow. Dollar’s Skid Puts a Glow on the Euro. Texas: 2001 Accident Survivor Dies. China: Venture to Build Vans. Sensing Opportunity in Dormitory Air. Ethiopian Premier Says His Troops Won’t Stay in Somalia. Iraq Sets Toll of Civilians at 12,000 for 2006. Cancer Patients&#8217; Wait Times Cost Billions. France: Pork Soup Handouts Not Racist, Court Says. Iraq Defends Hussein Execution, but Detains Guard. Man Sentenced to 26 Years for Reporter’s Murder. Spain: Peace Process With ETA ‘Broken’ by Bomb. U.S. and Brazil to Talk About Talks. Names of the Dead. EGL Gets Buyout Bid From Its Chief. Data on Hispanic Immigrants Presents Puzzle on Aging. The Philippines: U.S. Military Exercises to Resume. Venezuela: 16 Dead in Prison Melee. U.N. Panel Eases Caviar Ban. Trying to Regain Initiative, Bush Looks Ahead. Chrysler Is Only U.S. Carmaker to See Sales Gains. Enron's Last Victim: American Markets. A Light Bulb Goes On. A Surprising Secret to a Long Life: Stay in School. Iraq to Review Hussein’s Execution. New U.N. Chief Invites Controversy by Declining to Oppose Hussein Execution. Layoffs Imminent at Philadelphia Inquirer. Britain: Suspect in Prostitute Killings Stays Jailed. Sri Lanka: Tigers Say Air Raids Killed 15 Civilians. France: Utility Remains in Play. Singapore: Growth Spurt in Quarter. Embattled Chief Executive Resigns at Home Depot. White House Says It Would Have Handled Execution Differently. Qualcomm Under Scrutiny by Korean Antitrust Agency. Now It’s Belarus’s Turn. After the Rip van Winkle Years. Amgen Acquires Option for a Heart Failure Drug. Michigan: Man Rescued From Trash Truck. Saudi Arabia: Hajj Ends Without Incident. Afghanistan: Taliban Commander Vows Bloody 2007. Ford Is Remembered at Funeral in Washington. A Time of Temptation for the Thrifty of Ireland. When She Speaks, He’s Breaking All of Islam’s Taboos. This Is Your Brain on Drugs, Dad. Bag Handlers Held in Theft of Luggage in Houston. It’s the Year to Keep an Eye on Paychecks. Louisiana: Death of Mayor-Elect Is Ruled a Suicide. A Hanging and a Funeral. Lennar, Citing Weak Housing Market, Expects a Quarterly Loss. Shifts in Stock Indexes. Few Get Top Federal Marks for Disaster Planning. Nucor Agrees to Buy Harris Steel of Canada for $1.07 Billion. Stained Glass and Strained Egos. Indonesian Officials Now Say They Don’t Know Fate of Missing Jet. Starbucks Cuts Use of Trans Fats. Sick and Can’t Go to School? Or, Sick Because You Didn’t Go?. Blair’s Deputy Calls Taunting of Hussein at Execution ‘Deplorable’. Patent Lawsuit Names Leading Technology Firms. Fighting Over Gold in the Land of Dracula. Mexico: 3,000 Soldiers and Police to Tijuana. Lawsuit Claims Bid-Rigging in Tribe&#8217;s Purchase of Hard Rock. New Evidence of Liquid Methane on Saturn’s Moon. Sprint Nextel Puts Its Big Ad Account in Review. Serving Memory. An American University for Iraq but Not in Baghdad. Galvin Sees Broader Hedge-Fund Concerns. BenQ to Liquidate German Unit As White Knight Fails to Emerge. Indian Commodities Exchange Seeks Overseas Investor. Global Rally on First Day of Trading in New Year. Unicredit Buys Stake in Moscow Bank. CheckFree Takes Carreker into the Fold. Alcatel-Lucent Close Deal for Nortel Unit. Undertaker to Start-Ups Evolves Amid Good Times for Entrepeneurs. A New Sheriff With a Different Agenda?. Venture-Backed I.P.O.'s on Deck Double. Refco Emerges From Bankruptcy. EGL Gets Buyout Bid From Its Chief. Layoffs Imminent at Philadelphia Inquirer. Shanghai May Overtake Hong Kong in I.P.O.'s This Year. Amgen Acquires Option for a Heart Failure Drug. Energy Investments Likely to Burn Even Hotter This Year. Industry Ventures Bags $105 Million for New Fund. ICV and Palladium Sell Eyewear Supplier Hilsinger. Apple, Google and Napster Named in Patent Lawsuit. Sharper Image Cuts Chief's Severance to Offset Options Gain. Qualcomm Under Scrutiny by Korean Antitrust Agency. Class Action Suits Hit All-Time Low in 2006. Enron Accountant Heads to Jail. Malone and Dolans Talk about Cable Networks Deal, Report Says. Home Depot's Chief Resigns as Proxy Fight Looms. The Democrats' Hill: First 100-plus Hours. The President Restates His Principles. 2008 Like It's Today: Lost and Found. The 'Tech Expert' Is Stumped. Kravis and Roberts on the Buyout Boom. Should U.S. C.E.O.'s Prepare for a Tougher 2007?. Second Life and the People's House. Goldman Sachs: An Embarassment of Riches?. Goldman, Citi Top List of 2006 M&A Deal Makers. A Golden Goodbye for Home Depot Chief. Should U.S. Airlines Give Foreign Owners a Try?. Revolving Door: Weil Gotshal. An Investment Banking Love Story. War Protest Mom Upstages Democrats. Turning a Statistic On Its Head. Teatime With Pelosi. Ethics Changes Proposed for House Trips, K Street"

In [4]:
df_stocks['prices'] = df_stocks['adj close'].apply(np.int64)

In [5]:
# selecting the prices and articles
df_stocks = df_stocks[['prices', 'articles']]

In [6]:
df_stocks.articles = df_stocks.articles.map(lambda x: x.lstrip('.-'))

In [7]:
df_stocks

            prices                                           articles
2007-01-01   12469   What Sticks from '06. Somalia Orders Islamist...
2007-01-02   12472   Heart Health: Vitamin Does Not Prevent Death ...
2007-01-03   12474   Google Answer to Filling Jobs Is an Algorithm...
2007-01-04   12480   Helping Make the Shift From Combat to Commerc...
2007-01-05   12398   Rise in Ethanol Raises Concerns About Corn as...
2007-01-06   12406   A Status Quo Secretary General. Best Buy and ...
2007-01-07   12414   THE COMMON APPLICATION; Typo.com. Jumbo Bonus...
2007-01-08   12423   VW Group’s Sales Rose Sharply in 2006. Consol...
2007-01-09   12416   The Claim:  Hot Leftovers Should Cool at Room...
2007-01-10   12442   Love Among the Ruins. Dell Says Plant a Tree,...
2007-01-11   12514   The Computer With a TV, and a Family's Virtua...
2007-01-12   12556   Make Them Fight All of Us. Hire by the Contra...
2007-01-13   12562   Blair Urges Britain to Pursue an Aggressive F...
2007-01-14   12569   Smoke Damage. Mr. Spitzer’s Task on Court Ref...
2007-01-15   12575   The Mentally Ill, Behind Bars. BP’s Chief to ...
2007-01-16   12582   King Day in Atlanta, ‘the One Without Mrs. Ki...
2007-01-17   12577   Racial Hate Feeds a Gang War’s Senseless Kill...
2007-01-18   12567   Taliban Detainee Says Rebel Chief Hides in Pa...
2007-01-19   12565   Data Breach Could Affect Millions of TJX Shop...
2007-01-20   12536   Archives of Spin. H.P. Chief Defends Timing o...
2007-01-21   12506   Connecticut’s Diaspora. Son of Dogs Playing P...
2007-01-22   12477   M dot Strange Finds a Way at Sundance. An Int...
2007-01-23   12533   2 Car Bombs Kill Scores at Packed Market in B...
2007-01-24   12621   Asian Rival Moves Past Las Vegas. Pennsylvani...
2007-01-25   12502   Quarterly Profit Surges at Cingular Wireless....
2007-01-26   12487   Renewal, in Real Estate and in Culture, for A...
2007-01-27   12488   Cracking the Books for Financial Aid to Colle...
2007-01-28   12489   First You Clear the Table. Delight in Science...
2007-01-29   12490   Courts Turn to Wikipedia, but Selectively. Te...
2007-01-30   12523   Can Humanity Survive? Want to Bet on It?. Awa...
...            ...                                                ...
2016-12-02   19170   Silicon Valley Chiefs Notably Absent From Tru...
2016-12-03   19185   Trump, Taiwan and China: The Controversy, Exp...
2016-12-04   19200   Hunting ‘Turr’ in Newfoundland’s Frigid Water...
2016-12-05   19216   Trump’s Meeting With Al Gore Gives Environmen...
2016-12-06   19251   Senate Republican Leaders Vow to Begin Repeal...
2016-12-07   19549   Can Congress Lift the Presidential Conflict o...
2016-12-08   19614   The Freaky Food Chain Behind Your Lobster Din...
2016-12-09   19756   Trump Spent Far Less Than Clinton, but Paid H...
2016-12-10   19770   As Turkey Cracks Down, Kurdish Mayors Pack Ba...
2016-12-11   19783   I.M.F. Chief Heads to Trial; Fed Is Expected ...
2016-12-12   19796   Pennsylvania and Wisconsin End Election Recou...
2016-12-13   19911   The Most Talked-About Debates of 2016. Wells ...
2016-12-14   19792   Can Trump Get Tough With China?. The Oakland ...
2016-12-15   19852   Hispanic Surnames on the Rise in U.S. as Immi...
2016-12-16   19843   Vine, the Six-Second Video App, Is Not Quite ...
2016-12-17   19856   Trump’s Win Helps Carve a Path to Washington ...
2016-12-18   19869   With Comic Book, Celebrities Pay Tribute to O...
2016-12-19   19883   Donald Trump and the C.I.A.. Vincent Viola, B...
2016-12-20   19974   Can Trump's Infrastructure Plan Work?. Volksw...
2016-12-21   19941   Совершенное орудие: как российская кибермощь ...
2016-12-22   19918   New Ebola Vaccine Gives 100 Percent Protectio...
2016-12-23   19933   Flurry of Settlements Over Toxic Mortgages Ma...
2016-12-24   19936   Jason Miller Backs Out of White House Communi...
2016-12-25   19939   Wielding Claims of ‘Fake News,’ Conservatives...
2016-12-26   19942   When One Party Has the Governor’s Mansion and...
2016-12-27   19945   Should the U.S. Embassy Be Moved From Tel Avi...
2016-12-28   19833   When Finding the Right Lawyer Seems Daunting,...
2016-12-29   19819   Does Empathy Guide or Hinder Moral Action?. C...
2016-12-30   19762   Shielding Seized Assets From Corruption’s Clu...
2016-12-31   19762  Terrorist Attack at Nightclub in Istanbul Kill...

[3653 rows x 2 columns]

In [8]:
df = df_stocks[['prices']].copy()
df

            prices
2007-01-01   12469
2007-01-02   12472
2007-01-03   12474
2007-01-04   12480
2007-01-05   12398
2007-01-06   12406
2007-01-07   12414
2007-01-08   12423
2007-01-09   12416
2007-01-10   12442
2007-01-11   12514
2007-01-12   12556
2007-01-13   12562
2007-01-14   12569
2007-01-15   12575
2007-01-16   12582
2007-01-17   12577
2007-01-18   12567
2007-01-19   12565
2007-01-20   12536
2007-01-21   12506
2007-01-22   12477
2007-01-23   12533
2007-01-24   12621
2007-01-25   12502
2007-01-26   12487
2007-01-27   12488
2007-01-28   12489
2007-01-29   12490
2007-01-30   12523
...            ...
2016-12-02   19170
2016-12-03   19185
2016-12-04   19200
2016-12-05   19216
2016-12-06   19251
2016-12-07   19549
2016-12-08   19614
2016-12-09   19756
2016-12-10   19770
2016-12-11   19783
2016-12-12   19796
2016-12-13   19911
2016-12-14   19792
2016-12-15   19852
2016-12-16   19843
2016-12-17   19856
2016-12-18   19869
2016-12-19   19883
2016-12-20   19974
2016-12-21   19941
2016-12-22   19918
2016-12-23   19933
2016-12-24   19936
2016-12-25   19939
2016-12-26   19942
2016-12-27   19945
2016-12-28   19833
2016-12-29   19819
2016-12-30   19762
2016-12-31   19762

[3653 rows x 1 columns]

In [9]:
# Adding new columns to the data frame
df["compound"] = ''
df["neg"] = ''
df["neu"] = ''
df["pos"] = ''

In [10]:
df

            prices compound neg neu pos
2007-01-01   12469
2007-01-02   12472
2007-01-03   12474
2007-01-04   12480
2007-01-05   12398
2007-01-06   12406
2007-01-07   12414
2007-01-08   12423
2007-01-09   12416
2007-01-10   12442
2007-01-11   12514
2007-01-12   12556
2007-01-13   12562
2007-01-14   12569
2007-01-15   12575
2007-01-16   12582
2007-01-17   12577
2007-01-18   12567
2007-01-19   12565
2007-01-20   12536
2007-01-21   12506
2007-01-22   12477
2007-01-23   12533
2007-01-24   12621
2007-01-25   12502
2007-01-26   12487
2007-01-27   12488
2007-01-28   12489
2007-01-29   12490
2007-01-30   12523
...            ...      ...  ..  ..  ..
2016-12-02   19170
2016-12-03   19185
2016-12-04   19200
2016-12-05   19216
2016-12-06   19251
2016-12-07   19549
2016-12-08   19614
2016-12-09   19756
2016-12-10   19770
2016-12-11   19783
2016-12-12   19796
2016-12-13   19911
2016-12-14   19792
2016-12-15   19852
2016-12-16   19843
2016-12-17   19856
2016-12-18   19869
2016-12-19   19883
2016-12-20   19974
2016-12-21   19941
2016-12-22   19918
2016-12-23   19933
2016-12-24   19936
2016-12-25   19939
2016-12-26   19942
2016-12-27   19945
2016-12-28   19833
2016-12-29   19819
2016-12-30   19762
2016-12-31   19762

[3653 rows x 5 columns]

In [11]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import unicodedata
sid = SentimentIntensityAnalyzer()
for date, row in df_stocks.T.iteritems():
    try:
        sentence = unicodedata.normalize('NFKD', df_stocks.loc[date, 'articles'])#.encode('ascii','ignore')
        ss = sid.polarity_scores(sentence)
        df.set_value(date, 'compound', ss['compound'])
        df.set_value(date, 'neg', ss['neg'])
        df.set_value(date, 'neu', ss['neu'])
        df.set_value(date, 'pos', ss['pos'])
    except TypeError:
        print( df_stocks.loc[date, 'articles'])
        print (date)

In [12]:
# sentence = 'paris shootout police officer suspected guman dead'
# from nltk.sentiment.vader import SentimentIntensityAnalyzer
# import unicodedata
# sid = SentimentIntensityAnalyzer()
# ss = sid.polarity_scores(sentence)
# ss

In [13]:
# Checking date for empty strings
# for date, row in df_stocks.T.iteritems():
#     if type(df_stocks.loc[date, 'articles']).__name__ == 'str':
#         print date

In [14]:
df

            prices compound    neg    neu    pos
2007-01-01   12469  -0.9735  0.153  0.748  0.099
2007-01-02   12472  -0.9702  0.122  0.786  0.092
2007-01-03   12474  -0.9994  0.203  0.736   0.06
2007-01-04   12480  -0.9982  0.131  0.806  0.062
2007-01-05   12398  -0.9901  0.124  0.794  0.082
2007-01-06   12406   -0.965  0.134  0.771  0.094
2007-01-07   12414  -0.9975  0.193  0.739  0.069
2007-01-08   12423  -0.9427  0.108  0.793  0.099
2007-01-09   12416  -0.9945  0.102  0.847  0.051
2007-01-10   12442  -0.9863  0.141  0.742  0.117
2007-01-11   12514   -0.998  0.128  0.814  0.057
2007-01-12   12556  -0.9985  0.156  0.783  0.061
2007-01-13   12562  -0.9893  0.146  0.794  0.059
2007-01-14   12569    -0.99  0.178  0.711  0.111
2007-01-15   12575  -0.2636  0.088   0.83  0.082
2007-01-16   12582  -0.9839  0.112  0.804  0.085
2007-01-17   12577  -0.9986  0.176  0.743  0.081
2007-01-18   12567  -0.9994  0.213    0.7  0.086
2007-01-19   12565  -0.9957  0.115  0.822  0.063
2007-01-20   12536  -0.9841  0.132  0.786  0.081
2007-01-21   12506  -0.9851   0.14  0.775  0.084
2007-01-22   12477  -0.5638  0.099  0.804  0.097
2007-01-23   12533  -0.9989  0.152  0.781  0.067
2007-01-24   12621  -0.9933   0.14  0.757  0.103
2007-01-25   12502  -0.9965  0.153  0.744  0.103
2007-01-26   12487   -0.997  0.143   0.78  0.077
2007-01-27   12488  -0.9808   0.13  0.802  0.067
2007-01-28   12489  -0.9816  0.153  0.752  0.095
2007-01-29   12490  -0.9359  0.135  0.739  0.126
2007-01-30   12523  -0.9992  0.183  0.727   0.09
...            ...      ...    ...    ...    ...
2016-12-02   19170  -0.9956  0.152  0.768   0.08
2016-12-03   19185  -0.9827   0.16  0.737  0.103
2016-12-04   19200  -0.9707   0.16  0.772  0.068
2016-12-05   19216  -0.9636  0.165  0.691  0.144
2016-12-06   19251  -0.9967  0.172  0.726  0.103
2016-12-07   19549  -0.9735  0.118  0.794  0.087
2016-12-08   19614  -0.9943  0.145  0.784  0.071
2016-12-09   19756  -0.9968  0.173  0.726  0.101
2016-12-10   19770  -0.9952  0.171  0.747  0.082
2016-12-11   19783  -0.0772  0.099  0.808  0.093
2016-12-12   19796  -0.9697  0.126  0.775    0.1
2016-12-13   19911  -0.9986  0.173   0.76  0.067
2016-12-14   19792  -0.9674  0.121    0.8   0.08
2016-12-15   19852  -0.9925  0.121  0.833  0.046
2016-12-16   19843  -0.9896  0.141  0.776  0.083
2016-12-17   19856  -0.9553  0.119  0.793  0.088
2016-12-18   19869  -0.9884  0.206   0.73  0.064
2016-12-19   19883  -0.9944   0.15   0.77   0.08
2016-12-20   19974  -0.9874  0.125  0.814  0.061
2016-12-21   19941  -0.9955  0.153  0.776  0.071
2016-12-22   19918  -0.9983  0.199  0.724  0.077
2016-12-23   19933  -0.9902  0.159  0.735  0.106
2016-12-24   19936  -0.9234  0.152  0.748    0.1
2016-12-25   19939  -0.9894  0.175  0.775  0.049
2016-12-26   19942  -0.9453  0.148  0.744  0.107
2016-12-27   19945  -0.9898  0.178  0.719  0.103
2016-12-28   19833   0.2869  0.128  0.763  0.108
2016-12-29   19819  -0.9789  0.138  0.764  0.097
2016-12-30   19762  -0.9959  0.173  0.733  0.094
2016-12-31   19762  -0.2869  0.173  0.665  0.161

[3653 rows x 5 columns]

In [15]:
train_start_date = '2007-01-01'
train_end_date = '2014-12-31'
test_start_date = '2015-01-01'
test_end_date = '2016-12-31'
train = df.ix[train_start_date : train_end_date]
test = df.ix[test_start_date:test_end_date]

/home/batman/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """

In [16]:
sentiment_score_list = []
for date, row in train.T.iteritems():
    #sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
    sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
    sentiment_score_list.append(sentiment_score)
numpy_df_train = np.asarray(sentiment_score_list)

In [17]:
sentiment_score_list = []
for date, row in test.T.iteritems():
    #sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
    sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
    sentiment_score_list.append(sentiment_score)
numpy_df_test = np.asarray(sentiment_score_list)

In [18]:
y_train = pd.DataFrame(train['prices'])
y_test = pd.DataFrame(test['prices'])

In [19]:
from treeinterpreter import treeinterpreter as ti
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import classification_report,confusion_matrix

rf = RandomForestRegressor()
rf.fit(numpy_df_train, y_train)

/home/batman/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [21]:
print (rf.feature_importances_)

[ 0.54323112  0.45676888]

In [22]:
prediction, bias, contributions = ti.predict(rf, numpy_df_test)

In [ ]:
prediction

In [ ]:
contributions

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
idx = pd.date_range(test_start_date, test_end_date)
predictions_df = pd.DataFrame(data=prediction[0:], index = idx, columns=['prices'])

In [ ]:
predictions_df

In [ ]:
#predictions_df.plot() 
#test['prices'].plot()

predictions_plot = predictions_df.plot()

fig = y_test.plot(ax = predictions_plot).get_figure()
fig.savefig("graphs/random forest without smoothing.png")

In [ ]:
ax = predictions_df.rename(columns={"prices": "predicted_price"}).plot(title='Random Forest predicted prices 8-2 years')
ax.set_xlabel("Dates")
ax.set_ylabel("Stock Prices")
fig = y_test.rename(columns={"prices": "actual_price"}).plot(ax = ax).get_figure()
fig.savefig("graphs/random forest without smoothing.png")

# colors = ['332288', '88CCEE', '44AA99', '117733', '999933', 'DDCC77', 'CC6677', '882255', 'AA4499']

In [ ]:
test

# Increasing the prices by a constant value so that it represents closing price during the testing

In [ ]:
from datetime import datetime, timedelta

temp_date = test_start_date
average_last_5_days_test = 0
total_days = 10
for i in range(total_days):
    average_last_5_days_test += test.loc[temp_date, 'prices']
    # Converting string to date time
    temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
    # Reducing one day from date time
    difference = temp_date + timedelta(days=1)
    # Converting again date time to string
    temp_date = difference.strftime('%Y-%m-%d')
    #print temp_date
average_last_5_days_test = average_last_5_days_test / total_days
print average_last_5_days_test

temp_date = test_start_date
average_upcoming_5_days_predicted = 0
for i in range(total_days):
    average_upcoming_5_days_predicted += predictions_df.loc[temp_date, 'prices']
    # Converting string to date time
    temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
    # Adding one day from date time
    difference = temp_date + timedelta(days=1)
    # Converting again date time to string
    temp_date = difference.strftime('%Y-%m-%d')
    print temp_date
average_upcoming_5_days_predicted = average_upcoming_5_days_predicted / total_days
print average_upcoming_5_days_predicted
#average train.loc['2013-12-31', 'prices'] - advpredictions_df.loc['2014-01-01', 'prices']
difference_test_predicted_prices = average_last_5_days_test - average_upcoming_5_days_predicted
print difference_test_predicted_prices

In [ ]:
predictions_df

In [ ]:
# Adding 6177 to all the advpredictions_df price values
predictions_df['prices'] = predictions_df['prices'] + difference_test_predicted_prices
predictions_df

In [ ]:
ax = predictions_df.rename(columns={"prices": "predicted_price"}).plot(title='Random Forest predicted prices 8-2 years after aligning')
ax.set_xlabel("Dates")
ax.set_ylabel("Stock Prices")
fig = y_test.rename(columns={"prices": "actual_price"}).plot(ax = ax).get_figure()
fig.savefig("graphs/random forest with aligning.png")

# Smoothing the time series data

# Applying EWMA pandas to smooth the stock prices

In [ ]:
predictions_df

In [ ]:
predictions_df['ewma'] = pd.ewma(predictions_df["prices"], span=60, freq="D")

In [ ]:
predictions_df

In [ ]:
predictions_df['actual_value'] = test['prices']
predictions_df['actual_value_ewma'] = pd.ewma(predictions_df["actual_value"], span=60, freq="D")

In [ ]:
predictions_df

In [ ]:
# Changing column names
predictions_df.columns = ['predicted_price', 'average_predicted_price', 'actual_price', 'average_actual_price']

In [ ]:
# Now plotting test predictions after smoothing
predictions_plot = predictions_df.plot(title='Random Forest predicted prices 8-2 years after aligning & smoothing')
predictions_plot.set_xlabel("Dates")
predictions_plot.set_ylabel("Stock Prices")
fig = predictions_plot.get_figure()
fig.savefig("graphs/random forest after smoothing.png")

In [ ]:
# Plotting just predict and actual average curves
predictions_df_average = predictions_df[['average_predicted_price', 'average_actual_price']]
predictions_plot = predictions_df_average.plot(title='Random Forest 8-2 years after aligning & smoothing')
predictions_plot.set_xlabel("Dates")
predictions_plot.set_ylabel("Stock Prices")
fig = predictions_plot.get_figure()
fig.savefig("graphs/random forest after smoothing 2.png")

# Increasing the prices by a constant value so that it represents closing price during the testing

In [ ]:
def offset_value(test_start_date, test, predictions_df):
    temp_date = test_start_date
    average_last_5_days_test = 0
    average_upcoming_5_days_predicted = 0
    total_days = 10
    for i in range(total_days):
        average_last_5_days_test += test.loc[temp_date, 'prices']
        temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
        difference = temp_date + timedelta(days=1)
        temp_date = difference.strftime('%Y-%m-%d')
    average_last_5_days_test = average_last_5_days_test / total_days

    temp_date = test_start_date
    for i in range(total_days):
        average_upcoming_5_days_predicted += predictions_df.loc[temp_date, 'prices']
        temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
        difference = temp_date + timedelta(days=1)
        temp_date = difference.strftime('%Y-%m-%d')
    average_upcoming_5_days_predicted = average_upcoming_5_days_predicted / total_days
    difference_test_predicted_prices = average_last_5_days_test - average_upcoming_5_days_predicted
    return difference_test_predicted_prices

# LogisticRegression

In [ ]:
from treeinterpreter import treeinterpreter as ti
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from datetime import datetime, timedelta

# average_upcoming_5_days_predicted += predictions_df.loc[temp_date, 'prices']
# # Converting string to date time
# temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
# # Adding one day from date time
# difference = temp_date + timedelta(days=1)
# # Converting again date time to string
# temp_date = difference.strftime('%Y-%m-%d')
        
# start_year = datetime.strptime(train_start_date, "%Y-%m-%d").date().month

years = [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
prediction_list = []
for year in years:
    # Splitting the training and testing data
    train_start_date = str(year) + '-01-01'
    train_end_date = str(year) + '-10-31'
    test_start_date = str(year) + '-11-01'
    test_end_date = str(year) + '-12-31'
    train = df.ix[train_start_date : train_end_date]
    test = df.ix[test_start_date:test_end_date]
    
    # Calculating the sentiment score
    sentiment_score_list = []
    for date, row in train.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_train = np.asarray(sentiment_score_list)
    sentiment_score_list = []
    for date, row in test.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_test = np.asarray(sentiment_score_list)
    
    # Generating models
    lr = LogisticRegression()
    lr.fit(numpy_df_train, train['prices'])
    

    prediction = lr.predict(numpy_df_test)
    prediction_list.append(prediction)
    #print train_start_date + ' ' + train_end_date + ' ' + test_start_date + ' ' + test_end_date
    idx = pd.date_range(test_start_date, test_end_date)
    #print year
    predictions_df_list = pd.DataFrame(data=prediction[0:], index = idx, columns=['prices'])
    
    difference_test_predicted_prices = offset_value(test_start_date, test, predictions_df_list)
    # Adding offset to all the advpredictions_df price values
    predictions_df_list['prices'] = predictions_df_list['prices'] + difference_test_predicted_prices
    predictions_df_list

    # Smoothing the plot
    predictions_df_list['ewma'] = pd.ewma(predictions_df_list["prices"], span=10, freq="D")
    predictions_df_list['actual_value'] = test['prices']
    predictions_df_list['actual_value_ewma'] = pd.ewma(predictions_df_list["actual_value"], span=10, freq="D")
    # Changing column names
    predictions_df_list.columns = ['predicted_price', 'average_predicted_price', 'actual_price', 'average_actual_price']
    predictions_df_list.plot()
    predictions_df_list_average = predictions_df_list[['average_predicted_price', 'average_actual_price']]
    predictions_df_list_average.plot()
    
#     predictions_df_list.show()

In [ ]:
lr.classes_

In [ ]:
lr.coef_[0]

# RandomForestRegressor

In [ ]:
from treeinterpreter import treeinterpreter as ti
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from datetime import datetime, timedelta

# average_upcoming_5_days_predicted += predictions_df.loc[temp_date, 'prices']
# # Converting string to date time
# temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
# # Adding one day from date time
# difference = temp_date + timedelta(days=1)
# # Converting again date time to string
# temp_date = difference.strftime('%Y-%m-%d')
        
# start_year = datetime.strptime(train_start_date, "%Y-%m-%d").date().month

years = [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
prediction_list = []
for year in years:
    # Splitting the training and testing data
    train_start_date = str(year) + '-01-01'
    train_end_date = str(year) + '-10-31'
    test_start_date = str(year) + '-11-01'
    test_end_date = str(year) + '-12-31'
    train = df.ix[train_start_date : train_end_date]
    test = df.ix[test_start_date:test_end_date]
    
    # Calculating the sentiment score
    sentiment_score_list = []
    for date, row in train.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_train = np.asarray(sentiment_score_list)
    sentiment_score_list = []
    for date, row in test.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_test = np.asarray(sentiment_score_list)
    
    # Generating models
    rf = RandomForestRegressor(random_state=)
    rf.fit(numpy_df_train, train['prices'])
    #print rf
    
    prediction, bias, contributions = ti.predict(rf, numpy_df_test)
    prediction_list.append(prediction)
    #print train_start_date + ' ' + train_end_date + ' ' + test_start_date + ' ' + test_end_date
    idx = pd.date_range(test_start_date, test_end_date)
    #print year
    predictions_df_list = pd.DataFrame(data=prediction[0:], index = idx, columns=['prices'])
    
    difference_test_predicted_prices = offset_value(test_start_date, test, predictions_df_list)
    # Adding offset to all the advpredictions_df price values
    predictions_df_list['prices'] = predictions_df_list['prices'] + difference_test_predicted_prices
    predictions_df_list

    # Smoothing the plot
    predictions_df_list['ewma'] = pd.ewma(predictions_df_list["prices"], span=10, freq="D")
    predictions_df_list['actual_value'] = test['prices']
    predictions_df_list['actual_value_ewma'] = pd.ewma(predictions_df_list["actual_value"], span=10, freq="D")
    # Changing column names
    predictions_df_list.columns = ['predicted_price', 'average_predicted_price', 'actual_price', 'average_actual_price']
    predictions_df_list.plot()
    predictions_df_list_average = predictions_df_list[['average_predicted_price', 'average_actual_price']]
    predictions_df_list_average.plot()
    
#     predictions_df_list.show()

In [ ]:
# from IPython.display import Image  
# dot_data = tree.export_graphviz(rf, out_file=None, 
#                      feature_names=['comp', 'neg', 'neu', 'pos'],  
#                      class_names=iris.target_names,  
#                      filled=True, rounded=True,  
#                      special_characters=True)  
# graph = pydotplus.graph_from_dot_data(dot_data)  
# Image(graph.create_png())

# MLP Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier
from datetime import datetime, timedelta

# average_upcoming_5_days_predicted += predictions_df.loc[temp_date, 'prices']
# # Converting string to date time
# temp_date = datetime.strptime(temp_date, "%Y-%m-%d").date()
# # Adding one day from date time
# difference = temp_date + timedelta(days=1)
# # Converting again date time to string
# temp_date = difference.strftime('%Y-%m-%d')
        
# start_year = datetime.strptime(train_start_date, "%Y-%m-%d").date().month

years = [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016]
prediction_list = []
for year in years:
    # Splitting the training and testing data
    train_start_date = str(year) + '-01-01'
    train_end_date = str(year) + '-10-31'
    test_start_date = str(year) + '-11-01'
    test_end_date = str(year) + '-12-31'
    train = df.ix[train_start_date : train_end_date]
    test = df.ix[test_start_date:test_end_date]
    
    # Calculating the sentiment score
    sentiment_score_list = []
    for date, row in train.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_train = np.asarray(sentiment_score_list)
    sentiment_score_list = []
    for date, row in test.T.iteritems():
        sentiment_score = np.asarray([df.loc[date, 'compound'],df.loc[date, 'neg'],df.loc[date, 'neu'],df.loc[date, 'pos']])
        #sentiment_score = np.asarray([df.loc[date, 'neg'],df.loc[date, 'pos']])
        sentiment_score_list.append(sentiment_score)
    numpy_df_test = np.asarray(sentiment_score_list)
    
    # Generating models
    mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 100), activation='relu', 
                         solver='lbfgs', alpha=0.005, learning_rate_init = 0.001, shuffle=False) # span = 20 # best 1
    mlpc.fit(numpy_df_train, train['prices'])   
    prediction = mlpc.predict(numpy_df_test)
    
    prediction_list.append(prediction)
    #print train_start_date + ' ' + train_end_date + ' ' + test_start_date + ' ' + test_end_date
    idx = pd.date_range(test_start_date, test_end_date)
    #print year
    predictions_df_list = pd.DataFrame(data=prediction[0:], index = idx, columns=['prices'])
    
    difference_test_predicted_prices = offset_value(test_start_date, test, predictions_df_list)
    # Adding offset to all the advpredictions_df price values
    predictions_df_list['prices'] = predictions_df_list['prices'] + difference_test_predicted_prices
    predictions_df_list

    # Smoothing the plot
    predictions_df_list['ewma'] = pd.ewma(predictions_df_list["prices"], span=20, freq="D")
    predictions_df_list['actual_value'] = test['prices']
    predictions_df_list['actual_value_ewma'] = pd.ewma(predictions_df_list["actual_value"], span=20, freq="D")
    # Changing column names
    predictions_df_list.columns = ['predicted_price', 'average_predicted_price', 'actual_price', 'average_actual_price']
    predictions_df_list.plot()
    predictions_df_list_average = predictions_df_list[['average_predicted_price', 'average_actual_price']]
    predictions_df_list_average.plot()
    
#     predictions_df_list.show()

In [ ]:
mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 100), activation='tanh', 
                         solver='lbfgs', alpha=0.010, learning_rate_init = 0.001, shuffle=False)
mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 100), activation='relu', 
                         solver='lbfgs', alpha=0.010, learning_rate_init = 0.001, shuffle=False) # span = 20
mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 100), activation='relu', 
                         solver='lbfgs', alpha=0.005, learning_rate_init = 0.001, shuffle=False) # span = 20 # best 1
mlpc = MLPClassifier(hidden_layer_sizes=(100, 200, 50), activation='relu', 
                         solver='lbfgs', alpha=0.005, learning_rate_init = 0.001, shuffle=False

In [ ]:
# checking the performance of training data itself
prediction, bias, contributions = ti.predict(rf, numpy_df_train)
idx = pd.date_range(train_start_date, train_end_date)
predictions_df1 = pd.DataFrame(data=prediction[0:], index = idx, columns=['prices'])
predictions_df1.plot() 
train['prices'].plot()